Adding more language support and fixing install.sh

diff --git a/bin/beerunner b/bin/beerunner
--- a/bin/beerunner
+++ b/bin/beerunner
@@ -1,131 +1,194 @@
 #!/usr/bin/env bash
 
-# Global read-only variables
-declare -gr VERSION='0.0.1'
-declare -gr ARGV=("$@")
-declare -gr FILE="${ARGV[-1]}"
-declare -gr FILE_EXTENSION="${FILE##*.}"
+# Passed an argument?
+if [ "$#" -eq 0 ]
+then
+	echo "You need to pass a file"
+	exit 1
+fi
 
 # Global variables
-declare -g directory
-declare -g compiler
-declare -g interpreter
-declare -g file_extension
+declare -gr FILE_NAME="$1"
+declare -gr FILE_EXTANSION="${FILE_NAME//*.}"
 
-declare -i num_args=0
+# Global messages
+declare -gr MESSAGE_END='End of program'
+declare -gr MESSAGE_ERROR='An error occurred'
 
-# Private utility function
-function __command_exist {
-    if eval "type -P "$1" &> /dev/null"
-    then
-        return 0
-    fi
+# Start subroutines to run the source code
+function _c_lang {
+	local std_version
 
-    return 1
+	PS3='Please select your C version: '
+	select opt in 'DEFAULT C VERSION' 'C99'
+	do
+		case "$opt" in
+			'C99') std_version='-std=c99' ; break ;;
+			'DEFAULT C VERSION') std_version='' ; break ;;
+			*) echo "Invalid option: $REPLY" ;;
+		esac
+	done
+
+	echo "Creating the bin directory to put the executable"
+	eval "mkdir -p bin"
+	echo "Compiling C source code"
+	eval "gcc ${FILE_NAME} ${std_version} -O2 -lm -o bin/a.out" && {
+		echo "Running the executable"
+		eval "./bin/a.out"
+	} || {
+		echo "$MESSAGE_ERROR"
+		exit 1
+		}
+
+	echo "$MESSAGE_END"
 }
 
-# Help function
-function _help {
-    eval "cat << EOF
-Usage: $0 [OPTIONS] FILE
-A simple command line application to automaticly run a beecrowd exercise
-Options:
-    -i :     Choose your preferred interpreter
-    -d :     Choose the directory where to leave the executable
-    -c :     Choose your preferred compiler
-    -h :     Show this help message
-EOF"
-    exit 0
+function _cs_lang {
+	echo "Creating the bin directory to put the executable"
+	eval "mkdir -p bin"
+	echo "Compiling C# source code"
+	eval "mcs ${FILE_NAME} -out:bin/a.out" && {
+		echo "Running the executable"
+		eval "./bin/a.out"
+	} || {
+		echo "$MESSAGE_ERROR"
+		exit 1
+	}
+
+	echo "$MESSAGE_END"
 }
 
-# Functions for running languages
-function _c_run {
-    local path_executable
+function _cpp_lang {
+	local std_version
 
-    [ -z "$directory" ] && path_executable='a.out' || path_executable="${directory}/a.out"
-    [ -z "$compiler" ] && compiler='gcc'
+	PS3='Please select your C++ version: '
+	select opt in 'c++11' 'c++17'
+	do
+		case "$opt" in
+			'c++11') std_version='-std=c++11' ; break ;;
+			'c++17') std_version='-std=c++17' ; break ;;
+			*) echo "Invalid option: $REPLY" ;;
+		esac
+	done
 
-    if ! __command_exist "$compiler"
-    then
-        echo "The $compiler compiler for the C language was not found."
-        exit 1
-    fi
+	echo "Creating the bin directory to put the executable"
+	eval "mkdir -p bin"
+	echo "Compiling C++ source code"
+	eval "c++ ${FILE_NAME} ${std_version} -O2 -lm -o bin/a.out" && {
+		echo "Running the executable"
+		eval "./bin/a.out"
+	} || {
+		echo "$MESSAGE_ERROR"
+		exit 1
+	}
 
-    if ! [ -d "$directory" ] && ! [ -z "$directory" ]
-    then
-        echo "$directory directory does not exist"
-        exit 1
-    fi
-
-    echo "[Compiling the $FILE with $compiler]"
-    eval "$compiler $FILE -O2 -lm -o $path_executable"
-    echo "[Running the executable $path_executable]"
-    eval "./${path_executable}"
-    echo "[End of $FILE execution]"
+	echo "$MESSAGE_END"
 }
 
-function _python_run {
-    [ -z "$interpreter" ] && interpreter='python3'
+function _clj_lang {
+	echo "Interpreting and running Clojure source code" 
+	eval "clojure ${FILE_NAME}" || {
+		echo "$MESSAGE_ERROR"
+		exit 1	
+	}
 
-    if ! __command_exist "$interpreter"
-    then
-        echo "The $interpreter interpreter for the python language was not found"
-        exit 1
-    fi
-
-    echo "[Interpreting and running the $FILE]"
-    eval "$interpreter $FILE"
-    echo "[End of $FILE execution]"
+	echo "$MESSAGE_END"
 }
 
-function _ruby_run {
-    [ -z "$interpreter" ] && interpreter='ruby'
+function _go_lang {
+	echo "Compiling Go source code and running it"
+	eval "go run ${FILE_NAME}" || {
+		echo "$MESSAGE_ERROR"
+		exit 1
+	}
 
-    if ! __command_exist "$interpreter"
-    then
-        echo "The $interpreter interpreter for the ruby language was not found"
-        exit 1
-    fi
-
-    echo "[Interpreting and running the $FILE]"
-    eval "$interpreter $FILE"
-    echo "[End of $FILE execution]"
+	echo "$MESSAGE_END"
 }
 
-# Option parser
-while getopts 'hd:c:i:' opt
-do
-    case "$opt" in
-        d) directory="$OPTARG" ; ((num_args++)) ;;
-        c) compiler="$OPTARG" ; ((num_args++)) ;;
-        i) interpreter="$OPTARG" ; ((num_args++)) ;;
-        h) _help ;;
-    esac
-done
+function _hs_lang {
+	echo "Compiling Haskell source code and running it"
+	eval "runhaskell ${FILE_NAME}" || {
+		echo "$MESSAGE_ERROR"
+		exit 1
+	}
 
-# Testing arguments and derivatives
-if ! eval "find "$FILE" -type f &> /dev/null"
-then
-    echo "Missing file argument (try --help)"
-    exit 1
-fi
+	echo "$MESSAGE_END"
+}
 
-if ! [ -f "$FILE" ]
-then
-    echo "$FILE file does not exist"
-    exit 1
-fi
+function _java_lang {
+	echo "Compiling Java source code and running it"
+	eval "java ${FILE_NAME}" || {
+		echo "$MESSAGE_ERROR"
+		exit 1
+	}
 
-if [ "$FILE_EXTENSION" == "$FILE" ]
-then
-    echo "Could not recognize language from file $FILE"
-    exit 1
-fi
+	echo "$MESSAGE_END"
+}
 
-# Main of the program
-case "$FILE_EXTENSION" in
-    'c') _c_run ;;
-    'py'|'pyt') _python_run ;;
-    'rb'|'ruby') _ruby_run ;;
-    *) echo 'This language is not yet supported' ; exit 1
+function _js_lang {
+	echo "Interpreting and running the JavaScript source code"
+	eval "node ${FILE_NAME}" || {
+		echo "$MESSAGE_ERROR"
+		exit 1
+	}
+
+	echo "$MESSAGE_END"
+}
+
+function _lua_lang {
+	echo "Interpreting and running the Lua source code"
+	eval "lua ${FILE_NAME}" || {
+		echo "$MESSAGE_ERROR"
+		exit 1
+	}
+
+	echo "$MESSAGE_END"
+}
+
+function _ml_lang {
+	echo "Compiling OCaml source code and running it"
+	eval "ocaml ${FILE_NAME}" || {
+		echo "$MESSAGE_ERROR"
+		exit 1
+	}
+
+	echo "$MESSAGE_END"
+}
+
+function _py_lang {
+	local python_version
+
+	PS3='Please select your Python version: '
+	select opt in 'version 3' 'version 3.9'
+	do
+		case "$opt" in
+			'version 3') python_version='3' ; break ;;
+			'version 3.9') python_version='3.9' ; break ;;
+			*) echo "Ivalid option: $REPLY" ;;
+		esac
+	done
+
+	echo "Interpreting and running the Python source code"
+	eval "python${python_version} ${FILE_NAME}" || {
+		echo "$MESSAGE_ERROR"
+		exit 1
+	}
+
+	echo "$MESSAGE_END"
+}
+
+# Main
+case "$FILE_EXTANSION" in
+	'c') _c_lang ;;
+	'cs') _cs_lang ;;
+	'cpp'|'cc') _cpp_lang ;;
+	'clj') _clj_lang ;;
+	'go') _go_lang ;;
+	'hs') _hs_lang ;;
+	'java') _java_lang ;;
+	'js') _js_lang ;;
+	'lua') _lua_lang ;;
+	'ml') _ml_lang ;;
+	'py'|'pyt') _py_lang ;;
+	*) echo "File type not known or not supported" ; exit 1 ;;
 esac
